#version: '3.7'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda-1
    command:
      - redpanda start
      - --smp 1  # Limits CPU usage
      - --memory 1G # Limits RAM
      # ... look up the port mapping 9092 and 9644 in Redpanda docs
      #here we are adding ports
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      #here we are registering internaal ports as redpanda for us admins and external ports as localhost for clients
      - --advertise-kafka-addr internal://redpanda-1:9092,external://localhost:19092
    ports:
      - "19092:19092" #clients
      - "9644:9644" #admins